export const ProductList = [
  {
    id: 1,
    name: "Strawberry",
    price: 3.0,
    category: "Fruits",
    image: "../src/assets/images/strawberry.png",
  },
  {
    id: 2,
    name: "Butter",
    price: 3.5,
    category: "Dairy",
    image: "../src/assets/images/butter.png",
  },
  {
    id: 3,
    name: "Eggs",
    price: 2.95,
    category: "Dairy",
    image: "../src/assets/images/eggs.png",
  },
  {
    id: 4,
    name: "Cabbage",
    price: 4.0,
    category: "Vegetables",
    image: "../src/assets/images/cabbage.png",
  },
  {
    id: 5,
    name: "Eggplant",
    price: 4.0,
    category: "Vegetables",
    image: "../src/assets/images/eggplant.png",
  },
  {
    id: 6,
    name: "Shrimp",
    price: 3.5,
    category: "SeaFood",
    image: "../src/assets/images/shrimp.png",
  },
  {
    id: 7,
    name: "Kiwi",
    price: 2.05,
    category: "Fruits",
    image: "../src/assets/images/kiwi.png",
  },
  {
    id: 8,
    name: "Green Capsicum",
    price: 4.0,
    category: "Vegetables",
    image: "../src/assets/images/capsicum.png",
  },
  {
    id: 9,
    name: "Broccoli",
    price: 2.0,
    category: "Vegetables",
    image: "../src/assets/images/broccoli.png",
  },
  {
    id: 10,
    name: "Yogurt",
    price: 3.0,
    category: "Dairy",
    image: "../src/assets/images/yogurt.png",
  },
  {
    id: 11,
    name: "Beef",
    price: 8.0,
    category: "Meat",
    image: "../src/assets/images/beef.png",
  },
  {
    id: 12,
    name: "Chicken Breast",
    price: 7.0,
    category: "Meat",
    image: "../src/assets/images/chicken-breast.png",
  },
  {
    id: 13,
    name: "Kale Leaves",
    price: 3.0,
    category: "Vegetables",
    image: "../src/assets/images/kale.png",
  },
  {
    id: 14,
    name: "Mozzarella Cheese",
    price: 7.0,
    category: "Dairy",
    image: "../src/assets/images/cheese.png",
  },
  {
    id: 15,
    name: "Condensed Milk",
    price: 5.0,
    category: "Dairy",
    image: "../src/assets/images/milk.png",
  },
  {
    id: 16,
    name: "Salmon Filet ",
    price: 4.0,
    category: "SeaFood",
    image: "../src/assets/images/salmon.png",
  },
  {
    id: 17,
    name: "Banana ",
    price: 2.0,
    category: "Fruits",
    image: "../src/assets/images/banana.png",
  },
  {
    id: 18,
    name: "Milk Bottle (3)",
    price: 8.0,
    category: "Dairy",
    image: "../src/assets/images/milkbottles.png",
  },
  {
    id: 19,
    name: "PineApple",
    price: 5.0,
    category: "Fruits",
    image: "../src/assets/images/pineapple.png",
  },
  {
    id: 20,
    name: "Tofu Cubes",
    price: 4.0,
    category: "Dairy",
    image: "../src/assets/images/tofu.png",
  },
  {
    id: 21,
    name: "Tilapia Fish",
    price: 3.0,
    category: "SeaFood",
    image: "../src/assets/images/tilapia.png",
  },
  {
    id: 22,
    name: "Slice Cheese",
    price: 5.0,
    category: "Dairy",
    image: "../src/assets/images/slice-cheese.png",
  },
  {
    id: 23,
    name: "Ricotta Cheese",
    price: 7.0,
    category: "Dairy",
    image: "../src/assets/images/ricotta-cheese.png",
  },
  {
    id: 24,
    name: "Grapes",
    price: 3.0,
    category: "Fruits",
    image: "../src/assets/images/grapes.png",
  },
  {
    id: 25,
    name: "Lettuce Leaf",
    price: 3.0,
    category: "Vegetables",
    image: "../src/assets/images/lettuce.png",
  },
];

export const Categories = [
  "All",
  ...new Set(ProductList.map((product) => product.category)),
];

